# Site settings
title: Mark's Exploration
email: wuhuihao@qq.com
description: > # this means to ignore newlines until "baseurl:"
  huihao's blog about java html javascript css life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wuhuihao.com" # the base hostname & protocol for your site
twitter_username: wuhuihao
github_username:  huihao

# Build settings
markdown: github
